### ISSUE TITLE
Why i enabled Metal API in encode function but my Coreml custom layer still run on CPU

### ISSUE THREAD

**Issue by Tengxu-Sun** [hollance/CoreML-Custom-Layers#8]
Hello, @hollance . 

I implement a custom `pytorch` layer on both CPU and GPU following [your amazing blog](https://machinethink.net/blog/coreml-custom-layers/). The cpu version works good, but when i implemented this op on GPU it cannot activate "encode" function. Always run on CPU.  I have checked the `coremltools.convert()` options with `compute_units=coremltools.ComputeUnit.CPU_AND_GPU`, but it still doesn't work.  Similar problems also mentioned in https://stackoverflow.com/questions/51019600/why-i-enabled-metal-api-but-my-coreml-custom-layer-still-run-on-cpu and https://developer.apple.com/forums/thread/695640.   Any idea on help this would be grateful.

## System Information
- mac OS: 11.6.1 Big Sur
- xcode: 12.5.1
- coremltools: 5.1.0
- test device:  iphone 11

Update: I test your [GPU code example](https://github.com/hollance/CoreML-Custom-Layers/tree/master/2%20-%20App%20(GPU)), but it seems also execute in CPU ComputeUnit. Output are show below:
```
2022-01-12 17:04:02.593909+0800 CustomLayers[1515:575421] Metal GPU Frame Capture Enabled
2022-01-12 17:04:02.594216+0800 CustomLayers[1515:575421] Metal API Validation Enabled
init(parameters:) ["beta": 0.01, "engineName": Swish]
outputShapes(forInputShapes:) [[0, 0, 0, 0, 0]]
outputShapes(forInputShapes:) [[0, 0, 0, 0, 0]]
init(parameters:) ["beta": 0.01, "engineName": Swish]
init(parameters:) ["engineName": Swish, "beta": 0.01]
outputShapes(forInputShapes:) [[0, 0, 0, 0, 0]]
outputShapes(forInputShapes:) [[0, 0, 0, 0, 0]]
init(parameters:) ["beta": 0.01, "engineName": Swish]
setWeightData(_:) []
outputShapes(forInputShapes:) [[1, 1, 6, 256, 256]]
outputShapes(forInputShapes:) [[1, 1, 6, 256, 256]]
outputShapes(forInputShapes:) [[1, 1, 6, 256, 256]]
evaluate(inputs:outputs:) 1 1
Double 10 vector
[0.3277947902679443,0.03130210936069489,0.6019284725189209,0.001807634020224214,0.03013107925653458,0.001237826887518167,0.0006207154947333038,0.002744386438280344,0.001118888612836599,0.001314118970185518]
```

**Comment by hollance** [comment]
I am not Apple tech support. ;-)

But usually when this happens, there is some layer in the model that the GPU doesn't have a compute kernel for.

**Comment by Tengxu-Sun** [comment]
> 

Sorry for bother you, thanks a lot!
